// Code generated by ent, DO NOT EDIT.

package filtertype

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the filtertype type in the database.
	Label = "filter_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTechName holds the string denoting the tech_name field in the database.
	FieldTechName = "tech_name"
	// EdgeFilters holds the string denoting the filters edge name in mutations.
	EdgeFilters = "filters"
	// Table holds the table name of the filtertype in the database.
	Table = "filter_types"
	// FiltersTable is the table that holds the filters relation/edge.
	FiltersTable = "filters"
	// FiltersInverseTable is the table name for the Filter entity.
	// It exists in this package in order to avoid circular dependency with the "filter" package.
	FiltersInverseTable = "filters"
	// FiltersColumn is the table column denoting the filters relation/edge.
	FiltersColumn = "filter_filter_type"
)

// Columns holds all SQL columns for filtertype fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTechName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the FilterType queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTechName orders the results by the tech_name field.
func ByTechName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTechName, opts...).ToFunc()
}

// ByFiltersCount orders the results by filters count.
func ByFiltersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFiltersStep(), opts...)
	}
}

// ByFilters orders the results by filters terms.
func ByFilters(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFiltersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFiltersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FiltersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, FiltersTable, FiltersColumn),
	)
}
