// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString},
		{Name: "photo_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// FiltersColumns holds the columns for the "filters" table.
	FiltersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "filter_filter_type", Type: field.TypeInt},
	}
	// FiltersTable holds the schema information for the "filters" table.
	FiltersTable = &schema.Table{
		Name:       "filters",
		Columns:    FiltersColumns,
		PrimaryKey: []*schema.Column{FiltersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "filters_filter_types_filter_type",
				Columns:    []*schema.Column{FiltersColumns[2]},
				RefColumns: []*schema.Column{FilterTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// FilterTypesColumns holds the columns for the "filter_types" table.
	FilterTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "tech_name", Type: field.TypeString, Unique: true, Nullable: true},
	}
	// FilterTypesTable holds the schema information for the "filter_types" table.
	FilterTypesTable = &schema.Table{
		Name:       "filter_types",
		Columns:    FilterTypesColumns,
		PrimaryKey: []*schema.Column{FilterTypesColumns[0]},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "slug", Type: field.TypeString},
		{Name: "photo_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "product_category", Type: field.TypeInt},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "products_categories_category",
				Columns:    []*schema.Column{ProductsColumns[6]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ProductFiltersColumns holds the columns for the "product_filters" table.
	ProductFiltersColumns = []*schema.Column{
		{Name: "product_id", Type: field.TypeInt},
		{Name: "filter_id", Type: field.TypeInt},
	}
	// ProductFiltersTable holds the schema information for the "product_filters" table.
	ProductFiltersTable = &schema.Table{
		Name:       "product_filters",
		Columns:    ProductFiltersColumns,
		PrimaryKey: []*schema.Column{ProductFiltersColumns[0], ProductFiltersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "product_filters_product_id",
				Columns:    []*schema.Column{ProductFiltersColumns[0]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "product_filters_filter_id",
				Columns:    []*schema.Column{ProductFiltersColumns[1]},
				RefColumns: []*schema.Column{FiltersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		FiltersTable,
		FilterTypesTable,
		ProductsTable,
		ProductFiltersTable,
	}
)

func init() {
	FiltersTable.ForeignKeys[0].RefTable = FilterTypesTable
	ProductsTable.ForeignKeys[0].RefTable = CategoriesTable
	ProductFiltersTable.ForeignKeys[0].RefTable = ProductsTable
	ProductFiltersTable.ForeignKeys[1].RefTable = FiltersTable
}
