package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	product_backend "product-backend"
	"product-backend/ent"

	"entgo.io/contrib/entgql"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input ent.CreateCategoryInput) (*ent.Category, error) {
	return r.client.Category.Create().SetInput(input).Save(ctx)
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input ent.CreateProductInput) (*ent.Product, error) {
	return r.client.Product.Create().SetInput(input).Save(ctx)
}

// CreateFilter is the resolver for the createFilter field.
func (r *mutationResolver) CreateFilter(ctx context.Context, input ent.CreateFilterInput) (*ent.Filter, error) {
	return r.client.Filter.Create().SetInput(input).Save(ctx)
}

// CreateFilterType is the resolver for the createFilterType field.
func (r *mutationResolver) CreateFilterType(ctx context.Context, input ent.CreateFilterTypeInput) (*ent.FilterType, error) {
	return r.client.FilterType.Create().SetInput(input).Save(ctx)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id int, input ent.UpdateCategoryInput) (*ent.Category, error) {
	return r.client.Category.UpdateOneID(id).SetInput(input).Save(ctx)
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id int, input ent.UpdateProductInput) (*ent.Product, error) {
	return r.client.Product.UpdateOneID(id).SetInput(input).Save(ctx)
}

// UpdateFilter is the resolver for the updateFilter field.
func (r *mutationResolver) UpdateFilter(ctx context.Context, id int, input ent.UpdateFilterInput) (*ent.Filter, error) {
	return r.client.Filter.UpdateOneID(id).SetInput(input).Save(ctx)
}

// UpdateFilterType is the resolver for the updateFilterType field.
func (r *mutationResolver) UpdateFilterType(ctx context.Context, id int, input ent.UpdateFilterTypeInput) (*ent.FilterType, error) {
	return r.client.FilterType.UpdateOneID(id).SetInput(input).Save(ctx)
}

// ProductsByFilters is the resolver for the productsByFilters field.
func (r *queryResolver) ProductsByFilters(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.ProductWhereInput) (*ent.ProductConnection, error) {
	return r.client.Product.Query().Paginate(ctx, after, first, before, last, ent.WithProductFilter(where.Filter))
}

// Mutation returns product_backend.MutationResolver implementation.
func (r *Resolver) Mutation() product_backend.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
