package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	main "product-backend"
	"product-backend/ent"

	"entgo.io/contrib/entgql"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	return r.client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	return r.client.Noders(ctx, ids)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*ent.Category, error) {
	return r.client.Category.Query().All(ctx)
}

// Filters is the resolver for the filters field.
func (r *queryResolver) Filters(ctx context.Context) ([]*ent.Filter, error) {
	return r.client.Filter.Query().All(ctx)
}

// FilterTypes is the resolver for the filterTypes field.
func (r *queryResolver) FilterTypes(ctx context.Context) ([]*ent.FilterType, error) {
	return r.client.FilterType.Query().All(ctx)
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.ProductWhereInput) (*ent.ProductConnection, error) {
	return r.client.Product.Query().Paginate(ctx, after, first, before, last, ent.WithProductFilter(where.Filter))
}

// Query returns main.QueryResolver implementation.
func (r *Resolver) Query() main.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
