// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"product-backend/ent/filter"
	"product-backend/ent/filtertype"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Filter is the model entity for the Filter schema.
type Filter struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FilterQuery when eager-loading is set.
	Edges              FilterEdges `json:"edges"`
	filter_filter_type *int
	selectValues       sql.SelectValues
}

// FilterEdges holds the relations/edges for other nodes in the graph.
type FilterEdges struct {
	// FilterType holds the value of the filter_type edge.
	FilterType *FilterType `json:"filter_type,omitempty"`
	// Products holds the value of the products edge.
	Products []*Product `json:"products,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedProducts map[string][]*Product
}

// FilterTypeOrErr returns the FilterType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FilterEdges) FilterTypeOrErr() (*FilterType, error) {
	if e.FilterType != nil {
		return e.FilterType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: filtertype.Label}
	}
	return nil, &NotLoadedError{edge: "filter_type"}
}

// ProductsOrErr returns the Products value or an error if the edge
// was not loaded in eager-loading.
func (e FilterEdges) ProductsOrErr() ([]*Product, error) {
	if e.loadedTypes[1] {
		return e.Products, nil
	}
	return nil, &NotLoadedError{edge: "products"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Filter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case filter.FieldID:
			values[i] = new(sql.NullInt64)
		case filter.FieldName:
			values[i] = new(sql.NullString)
		case filter.ForeignKeys[0]: // filter_filter_type
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Filter fields.
func (_m *Filter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case filter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case filter.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case filter.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field filter_filter_type", value)
			} else if value.Valid {
				_m.filter_filter_type = new(int)
				*_m.filter_filter_type = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Filter.
// This includes values selected through modifiers, order, etc.
func (_m *Filter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFilterType queries the "filter_type" edge of the Filter entity.
func (_m *Filter) QueryFilterType() *FilterTypeQuery {
	return NewFilterClient(_m.config).QueryFilterType(_m)
}

// QueryProducts queries the "products" edge of the Filter entity.
func (_m *Filter) QueryProducts() *ProductQuery {
	return NewFilterClient(_m.config).QueryProducts(_m)
}

// Update returns a builder for updating this Filter.
// Note that you need to call Filter.Unwrap() before calling this method if this Filter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Filter) Update() *FilterUpdateOne {
	return NewFilterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Filter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Filter) Unwrap() *Filter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Filter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Filter) String() string {
	var builder strings.Builder
	builder.WriteString("Filter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// NamedProducts returns the Products named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Filter) NamedProducts(name string) ([]*Product, error) {
	if _m.Edges.namedProducts == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedProducts[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Filter) appendNamedProducts(name string, edges ...*Product) {
	if _m.Edges.namedProducts == nil {
		_m.Edges.namedProducts = make(map[string][]*Product)
	}
	if len(edges) == 0 {
		_m.Edges.namedProducts[name] = []*Product{}
	} else {
		_m.Edges.namedProducts[name] = append(_m.Edges.namedProducts[name], edges...)
	}
}

// Filters is a parsable slice of Filter.
type Filters []*Filter
