// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"product-backend/ent/filter"
	"product-backend/ent/filtertype"
	"product-backend/ent/predicate"
	"product-backend/ent/product"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FilterUpdate is the builder for updating Filter entities.
type FilterUpdate struct {
	config
	hooks    []Hook
	mutation *FilterMutation
}

// Where appends a list predicates to the FilterUpdate builder.
func (_u *FilterUpdate) Where(ps ...predicate.Filter) *FilterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *FilterUpdate) SetName(v string) *FilterUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FilterUpdate) SetNillableName(v *string) *FilterUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFilterTypeID sets the "filter_type" edge to the FilterType entity by ID.
func (_u *FilterUpdate) SetFilterTypeID(id int) *FilterUpdate {
	_u.mutation.SetFilterTypeID(id)
	return _u
}

// SetFilterType sets the "filter_type" edge to the FilterType entity.
func (_u *FilterUpdate) SetFilterType(v *FilterType) *FilterUpdate {
	return _u.SetFilterTypeID(v.ID)
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (_u *FilterUpdate) AddProductIDs(ids ...int) *FilterUpdate {
	_u.mutation.AddProductIDs(ids...)
	return _u
}

// AddProducts adds the "products" edges to the Product entity.
func (_u *FilterUpdate) AddProducts(v ...*Product) *FilterUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductIDs(ids...)
}

// Mutation returns the FilterMutation object of the builder.
func (_u *FilterUpdate) Mutation() *FilterMutation {
	return _u.mutation
}

// ClearFilterType clears the "filter_type" edge to the FilterType entity.
func (_u *FilterUpdate) ClearFilterType() *FilterUpdate {
	_u.mutation.ClearFilterType()
	return _u
}

// ClearProducts clears all "products" edges to the Product entity.
func (_u *FilterUpdate) ClearProducts() *FilterUpdate {
	_u.mutation.ClearProducts()
	return _u
}

// RemoveProductIDs removes the "products" edge to Product entities by IDs.
func (_u *FilterUpdate) RemoveProductIDs(ids ...int) *FilterUpdate {
	_u.mutation.RemoveProductIDs(ids...)
	return _u
}

// RemoveProducts removes "products" edges to Product entities.
func (_u *FilterUpdate) RemoveProducts(v ...*Product) *FilterUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FilterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FilterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FilterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FilterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FilterUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := filter.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Filter.name": %w`, err)}
		}
	}
	if _u.mutation.FilterTypeCleared() && len(_u.mutation.FilterTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Filter.filter_type"`)
	}
	return nil
}

func (_u *FilterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(filter.Table, filter.Columns, sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(filter.FieldName, field.TypeString, value)
	}
	if _u.mutation.FilterTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   filter.FilterTypeTable,
			Columns: []string{filter.FilterTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filtertype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilterTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   filter.FilterTypeTable,
			Columns: []string{filter.FilterTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filtertype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   filter.ProductsTable,
			Columns: filter.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductsIDs(); len(nodes) > 0 && !_u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   filter.ProductsTable,
			Columns: filter.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   filter.ProductsTable,
			Columns: filter.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FilterUpdateOne is the builder for updating a single Filter entity.
type FilterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FilterMutation
}

// SetName sets the "name" field.
func (_u *FilterUpdateOne) SetName(v string) *FilterUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FilterUpdateOne) SetNillableName(v *string) *FilterUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFilterTypeID sets the "filter_type" edge to the FilterType entity by ID.
func (_u *FilterUpdateOne) SetFilterTypeID(id int) *FilterUpdateOne {
	_u.mutation.SetFilterTypeID(id)
	return _u
}

// SetFilterType sets the "filter_type" edge to the FilterType entity.
func (_u *FilterUpdateOne) SetFilterType(v *FilterType) *FilterUpdateOne {
	return _u.SetFilterTypeID(v.ID)
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (_u *FilterUpdateOne) AddProductIDs(ids ...int) *FilterUpdateOne {
	_u.mutation.AddProductIDs(ids...)
	return _u
}

// AddProducts adds the "products" edges to the Product entity.
func (_u *FilterUpdateOne) AddProducts(v ...*Product) *FilterUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductIDs(ids...)
}

// Mutation returns the FilterMutation object of the builder.
func (_u *FilterUpdateOne) Mutation() *FilterMutation {
	return _u.mutation
}

// ClearFilterType clears the "filter_type" edge to the FilterType entity.
func (_u *FilterUpdateOne) ClearFilterType() *FilterUpdateOne {
	_u.mutation.ClearFilterType()
	return _u
}

// ClearProducts clears all "products" edges to the Product entity.
func (_u *FilterUpdateOne) ClearProducts() *FilterUpdateOne {
	_u.mutation.ClearProducts()
	return _u
}

// RemoveProductIDs removes the "products" edge to Product entities by IDs.
func (_u *FilterUpdateOne) RemoveProductIDs(ids ...int) *FilterUpdateOne {
	_u.mutation.RemoveProductIDs(ids...)
	return _u
}

// RemoveProducts removes "products" edges to Product entities.
func (_u *FilterUpdateOne) RemoveProducts(v ...*Product) *FilterUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductIDs(ids...)
}

// Where appends a list predicates to the FilterUpdate builder.
func (_u *FilterUpdateOne) Where(ps ...predicate.Filter) *FilterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FilterUpdateOne) Select(field string, fields ...string) *FilterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Filter entity.
func (_u *FilterUpdateOne) Save(ctx context.Context) (*Filter, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FilterUpdateOne) SaveX(ctx context.Context) *Filter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FilterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FilterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FilterUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := filter.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Filter.name": %w`, err)}
		}
	}
	if _u.mutation.FilterTypeCleared() && len(_u.mutation.FilterTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Filter.filter_type"`)
	}
	return nil
}

func (_u *FilterUpdateOne) sqlSave(ctx context.Context) (_node *Filter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(filter.Table, filter.Columns, sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Filter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, filter.FieldID)
		for _, f := range fields {
			if !filter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != filter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(filter.FieldName, field.TypeString, value)
	}
	if _u.mutation.FilterTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   filter.FilterTypeTable,
			Columns: []string{filter.FilterTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filtertype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilterTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   filter.FilterTypeTable,
			Columns: []string{filter.FilterTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filtertype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   filter.ProductsTable,
			Columns: filter.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductsIDs(); len(nodes) > 0 && !_u.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   filter.ProductsTable,
			Columns: filter.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   filter.ProductsTable,
			Columns: filter.ProductsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Filter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
