// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"product-backend/ent/filter"
	"product-backend/ent/filtertype"
	"product-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FilterTypeUpdate is the builder for updating FilterType entities.
type FilterTypeUpdate struct {
	config
	hooks    []Hook
	mutation *FilterTypeMutation
}

// Where appends a list predicates to the FilterTypeUpdate builder.
func (_u *FilterTypeUpdate) Where(ps ...predicate.FilterType) *FilterTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *FilterTypeUpdate) SetName(v string) *FilterTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FilterTypeUpdate) SetNillableName(v *string) *FilterTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTechName sets the "tech_name" field.
func (_u *FilterTypeUpdate) SetTechName(v string) *FilterTypeUpdate {
	_u.mutation.SetTechName(v)
	return _u
}

// SetNillableTechName sets the "tech_name" field if the given value is not nil.
func (_u *FilterTypeUpdate) SetNillableTechName(v *string) *FilterTypeUpdate {
	if v != nil {
		_u.SetTechName(*v)
	}
	return _u
}

// ClearTechName clears the value of the "tech_name" field.
func (_u *FilterTypeUpdate) ClearTechName() *FilterTypeUpdate {
	_u.mutation.ClearTechName()
	return _u
}

// AddFilterIDs adds the "filters" edge to the Filter entity by IDs.
func (_u *FilterTypeUpdate) AddFilterIDs(ids ...int) *FilterTypeUpdate {
	_u.mutation.AddFilterIDs(ids...)
	return _u
}

// AddFilters adds the "filters" edges to the Filter entity.
func (_u *FilterTypeUpdate) AddFilters(v ...*Filter) *FilterTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFilterIDs(ids...)
}

// Mutation returns the FilterTypeMutation object of the builder.
func (_u *FilterTypeUpdate) Mutation() *FilterTypeMutation {
	return _u.mutation
}

// ClearFilters clears all "filters" edges to the Filter entity.
func (_u *FilterTypeUpdate) ClearFilters() *FilterTypeUpdate {
	_u.mutation.ClearFilters()
	return _u
}

// RemoveFilterIDs removes the "filters" edge to Filter entities by IDs.
func (_u *FilterTypeUpdate) RemoveFilterIDs(ids ...int) *FilterTypeUpdate {
	_u.mutation.RemoveFilterIDs(ids...)
	return _u
}

// RemoveFilters removes "filters" edges to Filter entities.
func (_u *FilterTypeUpdate) RemoveFilters(v ...*Filter) *FilterTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFilterIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FilterTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FilterTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FilterTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FilterTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FilterTypeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := filtertype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FilterType.name": %w`, err)}
		}
	}
	return nil
}

func (_u *FilterTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(filtertype.Table, filtertype.Columns, sqlgraph.NewFieldSpec(filtertype.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(filtertype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TechName(); ok {
		_spec.SetField(filtertype.FieldTechName, field.TypeString, value)
	}
	if _u.mutation.TechNameCleared() {
		_spec.ClearField(filtertype.FieldTechName, field.TypeString)
	}
	if _u.mutation.FiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   filtertype.FiltersTable,
			Columns: []string{filtertype.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFiltersIDs(); len(nodes) > 0 && !_u.mutation.FiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   filtertype.FiltersTable,
			Columns: []string{filtertype.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FiltersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   filtertype.FiltersTable,
			Columns: []string{filtertype.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filtertype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FilterTypeUpdateOne is the builder for updating a single FilterType entity.
type FilterTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FilterTypeMutation
}

// SetName sets the "name" field.
func (_u *FilterTypeUpdateOne) SetName(v string) *FilterTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FilterTypeUpdateOne) SetNillableName(v *string) *FilterTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTechName sets the "tech_name" field.
func (_u *FilterTypeUpdateOne) SetTechName(v string) *FilterTypeUpdateOne {
	_u.mutation.SetTechName(v)
	return _u
}

// SetNillableTechName sets the "tech_name" field if the given value is not nil.
func (_u *FilterTypeUpdateOne) SetNillableTechName(v *string) *FilterTypeUpdateOne {
	if v != nil {
		_u.SetTechName(*v)
	}
	return _u
}

// ClearTechName clears the value of the "tech_name" field.
func (_u *FilterTypeUpdateOne) ClearTechName() *FilterTypeUpdateOne {
	_u.mutation.ClearTechName()
	return _u
}

// AddFilterIDs adds the "filters" edge to the Filter entity by IDs.
func (_u *FilterTypeUpdateOne) AddFilterIDs(ids ...int) *FilterTypeUpdateOne {
	_u.mutation.AddFilterIDs(ids...)
	return _u
}

// AddFilters adds the "filters" edges to the Filter entity.
func (_u *FilterTypeUpdateOne) AddFilters(v ...*Filter) *FilterTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFilterIDs(ids...)
}

// Mutation returns the FilterTypeMutation object of the builder.
func (_u *FilterTypeUpdateOne) Mutation() *FilterTypeMutation {
	return _u.mutation
}

// ClearFilters clears all "filters" edges to the Filter entity.
func (_u *FilterTypeUpdateOne) ClearFilters() *FilterTypeUpdateOne {
	_u.mutation.ClearFilters()
	return _u
}

// RemoveFilterIDs removes the "filters" edge to Filter entities by IDs.
func (_u *FilterTypeUpdateOne) RemoveFilterIDs(ids ...int) *FilterTypeUpdateOne {
	_u.mutation.RemoveFilterIDs(ids...)
	return _u
}

// RemoveFilters removes "filters" edges to Filter entities.
func (_u *FilterTypeUpdateOne) RemoveFilters(v ...*Filter) *FilterTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFilterIDs(ids...)
}

// Where appends a list predicates to the FilterTypeUpdate builder.
func (_u *FilterTypeUpdateOne) Where(ps ...predicate.FilterType) *FilterTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FilterTypeUpdateOne) Select(field string, fields ...string) *FilterTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FilterType entity.
func (_u *FilterTypeUpdateOne) Save(ctx context.Context) (*FilterType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FilterTypeUpdateOne) SaveX(ctx context.Context) *FilterType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FilterTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FilterTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FilterTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := filtertype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FilterType.name": %w`, err)}
		}
	}
	return nil
}

func (_u *FilterTypeUpdateOne) sqlSave(ctx context.Context) (_node *FilterType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(filtertype.Table, filtertype.Columns, sqlgraph.NewFieldSpec(filtertype.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FilterType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, filtertype.FieldID)
		for _, f := range fields {
			if !filtertype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != filtertype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(filtertype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TechName(); ok {
		_spec.SetField(filtertype.FieldTechName, field.TypeString, value)
	}
	if _u.mutation.TechNameCleared() {
		_spec.ClearField(filtertype.FieldTechName, field.TypeString)
	}
	if _u.mutation.FiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   filtertype.FiltersTable,
			Columns: []string{filtertype.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFiltersIDs(); len(nodes) > 0 && !_u.mutation.FiltersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   filtertype.FiltersTable,
			Columns: []string{filtertype.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FiltersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   filtertype.FiltersTable,
			Columns: []string{filtertype.FiltersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(filter.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FilterType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{filtertype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
