// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"product-backend/ent/filtertype"
	"product-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FilterTypeDelete is the builder for deleting a FilterType entity.
type FilterTypeDelete struct {
	config
	hooks    []Hook
	mutation *FilterTypeMutation
}

// Where appends a list predicates to the FilterTypeDelete builder.
func (_d *FilterTypeDelete) Where(ps ...predicate.FilterType) *FilterTypeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FilterTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FilterTypeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FilterTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(filtertype.Table, sqlgraph.NewFieldSpec(filtertype.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FilterTypeDeleteOne is the builder for deleting a single FilterType entity.
type FilterTypeDeleteOne struct {
	_d *FilterTypeDelete
}

// Where appends a list predicates to the FilterTypeDelete builder.
func (_d *FilterTypeDeleteOne) Where(ps ...predicate.FilterType) *FilterTypeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FilterTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{filtertype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FilterTypeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
