// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
)

// CreateCategoryInput represents a mutation input for creating categories.
type CreateCategoryInput struct {
	Name       string
	Slug       string
	PhotoURL   *string
	CreatedAt  *time.Time
	ProductIDs []int
}

// Mutate applies the CreateCategoryInput on the CategoryMutation builder.
func (i *CreateCategoryInput) Mutate(m *CategoryMutation) {
	m.SetName(i.Name)
	m.SetSlug(i.Slug)
	if v := i.PhotoURL; v != nil {
		m.SetPhotoURL(*v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.ProductIDs; len(v) > 0 {
		m.AddProductIDs(v...)
	}
}

// SetInput applies the change-set in the CreateCategoryInput on the CategoryCreate builder.
func (c *CategoryCreate) SetInput(i CreateCategoryInput) *CategoryCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateCategoryInput represents a mutation input for updating categories.
type UpdateCategoryInput struct {
	Name             *string
	Slug             *string
	ClearPhotoURL    bool
	PhotoURL         *string
	CreatedAt        *time.Time
	ClearProducts    bool
	AddProductIDs    []int
	RemoveProductIDs []int
}

// Mutate applies the UpdateCategoryInput on the CategoryMutation builder.
func (i *UpdateCategoryInput) Mutate(m *CategoryMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Slug; v != nil {
		m.SetSlug(*v)
	}
	if i.ClearPhotoURL {
		m.ClearPhotoURL()
	}
	if v := i.PhotoURL; v != nil {
		m.SetPhotoURL(*v)
	}
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if i.ClearProducts {
		m.ClearProducts()
	}
	if v := i.AddProductIDs; len(v) > 0 {
		m.AddProductIDs(v...)
	}
	if v := i.RemoveProductIDs; len(v) > 0 {
		m.RemoveProductIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateCategoryInput on the CategoryUpdate builder.
func (c *CategoryUpdate) SetInput(i UpdateCategoryInput) *CategoryUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateCategoryInput on the CategoryUpdateOne builder.
func (c *CategoryUpdateOne) SetInput(i UpdateCategoryInput) *CategoryUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateFilterInput represents a mutation input for creating filters.
type CreateFilterInput struct {
	Name         string
	FilterTypeID int
	ProductIDs   []int
}

// Mutate applies the CreateFilterInput on the FilterMutation builder.
func (i *CreateFilterInput) Mutate(m *FilterMutation) {
	m.SetName(i.Name)
	m.SetFilterTypeID(i.FilterTypeID)
	if v := i.ProductIDs; len(v) > 0 {
		m.AddProductIDs(v...)
	}
}

// SetInput applies the change-set in the CreateFilterInput on the FilterCreate builder.
func (c *FilterCreate) SetInput(i CreateFilterInput) *FilterCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateFilterInput represents a mutation input for updating filters.
type UpdateFilterInput struct {
	Name             *string
	FilterTypeID     *int
	ClearProducts    bool
	AddProductIDs    []int
	RemoveProductIDs []int
}

// Mutate applies the UpdateFilterInput on the FilterMutation builder.
func (i *UpdateFilterInput) Mutate(m *FilterMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.FilterTypeID; v != nil {
		m.SetFilterTypeID(*v)
	}
	if i.ClearProducts {
		m.ClearProducts()
	}
	if v := i.AddProductIDs; len(v) > 0 {
		m.AddProductIDs(v...)
	}
	if v := i.RemoveProductIDs; len(v) > 0 {
		m.RemoveProductIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateFilterInput on the FilterUpdate builder.
func (c *FilterUpdate) SetInput(i UpdateFilterInput) *FilterUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateFilterInput on the FilterUpdateOne builder.
func (c *FilterUpdateOne) SetInput(i UpdateFilterInput) *FilterUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateFilterTypeInput represents a mutation input for creating filtertypes.
type CreateFilterTypeInput struct {
	Name      string
	TechName  *string
	FilterIDs []int
}

// Mutate applies the CreateFilterTypeInput on the FilterTypeMutation builder.
func (i *CreateFilterTypeInput) Mutate(m *FilterTypeMutation) {
	m.SetName(i.Name)
	if v := i.TechName; v != nil {
		m.SetTechName(*v)
	}
	if v := i.FilterIDs; len(v) > 0 {
		m.AddFilterIDs(v...)
	}
}

// SetInput applies the change-set in the CreateFilterTypeInput on the FilterTypeCreate builder.
func (c *FilterTypeCreate) SetInput(i CreateFilterTypeInput) *FilterTypeCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateFilterTypeInput represents a mutation input for updating filtertypes.
type UpdateFilterTypeInput struct {
	Name            *string
	ClearTechName   bool
	TechName        *string
	ClearFilters    bool
	AddFilterIDs    []int
	RemoveFilterIDs []int
}

// Mutate applies the UpdateFilterTypeInput on the FilterTypeMutation builder.
func (i *UpdateFilterTypeInput) Mutate(m *FilterTypeMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if i.ClearTechName {
		m.ClearTechName()
	}
	if v := i.TechName; v != nil {
		m.SetTechName(*v)
	}
	if i.ClearFilters {
		m.ClearFilters()
	}
	if v := i.AddFilterIDs; len(v) > 0 {
		m.AddFilterIDs(v...)
	}
	if v := i.RemoveFilterIDs; len(v) > 0 {
		m.RemoveFilterIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateFilterTypeInput on the FilterTypeUpdate builder.
func (c *FilterTypeUpdate) SetInput(i UpdateFilterTypeInput) *FilterTypeUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateFilterTypeInput on the FilterTypeUpdateOne builder.
func (c *FilterTypeUpdateOne) SetInput(i UpdateFilterTypeInput) *FilterTypeUpdateOne {
	i.Mutate(c.Mutation())
	return c
}

// CreateProductInput represents a mutation input for creating products.
type CreateProductInput struct {
	Name        string
	Description *string
	Slug        string
	PhotoURL    *string
	CategoryID  int
	FilterIDs   []int
}

// Mutate applies the CreateProductInput on the ProductMutation builder.
func (i *CreateProductInput) Mutate(m *ProductMutation) {
	m.SetName(i.Name)
	if v := i.Description; v != nil {
		m.SetDescription(*v)
	}
	m.SetSlug(i.Slug)
	if v := i.PhotoURL; v != nil {
		m.SetPhotoURL(*v)
	}
	m.SetCategoryID(i.CategoryID)
	if v := i.FilterIDs; len(v) > 0 {
		m.AddFilterIDs(v...)
	}
}

// SetInput applies the change-set in the CreateProductInput on the ProductCreate builder.
func (c *ProductCreate) SetInput(i CreateProductInput) *ProductCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateProductInput represents a mutation input for updating products.
type UpdateProductInput struct {
	Name             *string
	ClearDescription bool
	Description      *string
	Slug             *string
	ClearPhotoURL    bool
	PhotoURL         *string
	CategoryID       *int
	ClearFilters     bool
	AddFilterIDs     []int
	RemoveFilterIDs  []int
}

// Mutate applies the UpdateProductInput on the ProductMutation builder.
func (i *UpdateProductInput) Mutate(m *ProductMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if i.ClearDescription {
		m.ClearDescription()
	}
	if v := i.Description; v != nil {
		m.SetDescription(*v)
	}
	if v := i.Slug; v != nil {
		m.SetSlug(*v)
	}
	if i.ClearPhotoURL {
		m.ClearPhotoURL()
	}
	if v := i.PhotoURL; v != nil {
		m.SetPhotoURL(*v)
	}
	if v := i.CategoryID; v != nil {
		m.SetCategoryID(*v)
	}
	if i.ClearFilters {
		m.ClearFilters()
	}
	if v := i.AddFilterIDs; len(v) > 0 {
		m.AddFilterIDs(v...)
	}
	if v := i.RemoveFilterIDs; len(v) > 0 {
		m.RemoveFilterIDs(v...)
	}
}

// SetInput applies the change-set in the UpdateProductInput on the ProductUpdate builder.
func (c *ProductUpdate) SetInput(i UpdateProductInput) *ProductUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateProductInput on the ProductUpdateOne builder.
func (c *ProductUpdateOne) SetInput(i UpdateProductInput) *ProductUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
