// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Category) Products(ctx context.Context) (result []*Product, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedProducts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ProductsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryProducts().All(ctx)
	}
	return result, err
}

func (_m *Filter) FilterType(ctx context.Context) (*FilterType, error) {
	result, err := _m.Edges.FilterTypeOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryFilterType().Only(ctx)
	}
	return result, err
}

func (_m *Filter) Products(ctx context.Context) (result []*Product, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedProducts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ProductsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryProducts().All(ctx)
	}
	return result, err
}

func (_m *FilterType) Filters(ctx context.Context) (result []*Filter, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedFilters(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.FiltersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryFilters().All(ctx)
	}
	return result, err
}

func (_m *Product) Category(ctx context.Context) (*Category, error) {
	result, err := _m.Edges.CategoryOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryCategory().Only(ctx)
	}
	return result, err
}

func (_m *Product) Filters(ctx context.Context) (result []*Filter, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedFilters(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.FiltersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryFilters().All(ctx)
	}
	return result, err
}
