// Code generated by ent, DO NOT EDIT.

package ent

import (
	"product-backend/ent/category"
	"product-backend/ent/filter"
	"product-backend/ent/filtertype"
	"product-backend/ent/product"
	"product-backend/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[0].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescSlug is the schema descriptor for slug field.
	categoryDescSlug := categoryFields[1].Descriptor()
	// category.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	category.SlugValidator = categoryDescSlug.Validators[0].(func(string) error)
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[3].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	filterFields := schema.Filter{}.Fields()
	_ = filterFields
	// filterDescName is the schema descriptor for name field.
	filterDescName := filterFields[0].Descriptor()
	// filter.NameValidator is a validator for the "name" field. It is called by the builders before save.
	filter.NameValidator = filterDescName.Validators[0].(func(string) error)
	filtertypeFields := schema.FilterType{}.Fields()
	_ = filtertypeFields
	// filtertypeDescName is the schema descriptor for name field.
	filtertypeDescName := filtertypeFields[0].Descriptor()
	// filtertype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	filtertype.NameValidator = filtertypeDescName.Validators[0].(func(string) error)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[0].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
	// productDescSlug is the schema descriptor for slug field.
	productDescSlug := productFields[2].Descriptor()
	// product.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	product.SlugValidator = productDescSlug.Validators[0].(func(string) error)
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[4].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
}
